apiVersion: v2
name: weather-app-auth
description: Authentication App for Weather App Microservice
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 9.16.1
    repository: https://charts.bitnami.com/bitnami
